apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::892861666869:role/eksctl-eksctl-demo-nodegroup-ng-d-NodeInstanceRole-1OA6SKRAN5P2D\n
    \ username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n
    \ rolearn: arn:aws:iam::892861666869:role/UdacityFlaskDeployCBKubectlRole\n  username:
    build \n"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-01T02:20:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "21118"
  uid: 4ef4a5c6-3e60-4f22-b0ca-27308f59a5c5
